title: Repository to learn how to configure github Pages
author: AntÃ³nio Santos
email: amn.santos@campus.fct.ubl.pt
description: > # this means to ignore newlines until "baseurl:"
  [You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.]

# social links
# twitter_username: your-twitter-handle
github_username: antoniomnds

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
